"use client";
import { useCallback, useEffect, useState } from "react";

type Appointment = { appointmentDate: string; appointmentTime: string; serviceName: string | null; serviceDuration: number | null; priceCents: number | null; customerName: string; customerEmail: string; customerPhone: string; barberName: string };
function prettyDate(value: string) { return new Intl.DateTimeFormat("es-ES", { weekday: "long", day: "numeric", month: "long" }).format(new Date(`${value}T12:00:00`)); }

export default function ManageAppointment({ token }: { token: string }) {
  const [appointment, setAppointment] = useState<Appointment | null>(null); const [date, setDate] = useState(""); const [time, setTime] = useState(""); const [times, setTimes] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [cancelled, setCancelled] = useState(false); const [updated, setUpdated] = useState(false);
  const load = useCallback(async (requestedDate?: string) => { const response = await fetch(`/api/manage/${token}${requestedDate ? `?date=${requestedDate}` : ""}`); const body = await response.json(); if (!response.ok) throw new Error(body.error); setAppointment(body.appointment); setTimes(body.availableTimes); if (!requestedDate) { setDate(body.appointment.appointmentDate); setTime(body.appointment.appointmentTime); } }, [token]);
  useEffect(() => { let active = true; fetch(`/api/manage/${token}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); if (active) { setAppointment(body.appointment); setTimes(body.availableTimes); setDate(body.appointment.appointmentDate); setTime(body.appointment.appointmentTime); } }).catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : "No se pudo cargar la cita."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [token]);
  async function changeDate(value: string) { setDate(value); setTime(""); setError(""); try { await load(value); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo consultar la disponibilidad."); } }
  async function save() { if (!date || !time) return; setSaving(true); setError(""); const response = await fetch(`/api/manage/${token}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "reschedule", date, time }) }); const body = await response.json(); if (!response.ok) setError(body.error); else { setUpdated(true); await load(); } setSaving(false); }
  async function cancel() { if (!window.confirm("¿Seguro que quieres cancelar tu cita? Esta acción no se puede deshacer.")) return; setSaving(true); const response = await fetch(`/api/manage/${token}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "cancel" }) }); if (response.ok) setCancelled(true); else { const body = await response.json(); setError(body.error); } setSaving(false); }
  if (loading) return <main className="manage-page"><div className="manage-card"><p>Cargando tu cita…</p></div></main>;
  if (cancelled) return <main className="manage-page"><div className="manage-card manage-result"><div className="andalusian-star"><i /><i /></div><h1>Cita cancelada</h1><p>La cita ha sido anulada correctamente y esa hora vuelve a estar disponible.</p></div></main>;
  if (!appointment) return <main className="manage-page"><div className="manage-card manage-result"><div className="andalusian-star"><i /><i /></div><h1>Enlace no válido</h1><p>{error}</p></div></main>;
  return <main className="manage-page"><section className="manage-card"><div className="booking-heading"><div className="andalusian-star"><i /><i /></div><p>GLORIA BENDITA</p><h1>Gestiona tu cita</h1><span>Este es tu enlace privado</span></div>{updated && <p className="manage-success">La cita se ha actualizado correctamente.</p>}<div className="current-appointment"><span>{appointment.appointmentTime}</span><div><b>{appointment.barberName}</b><small>{prettyDate(appointment.appointmentDate)}</small></div></div><div className="customer-summary"><span>{appointment.customerName}</span><span>{appointment.customerPhone}</span><span>{appointment.customerEmail}</span></div><div className="manage-form"><h2>Cambiar fecha u hora</h2><label>NUEVA FECHA<input type="date" value={date} min={new Date().toISOString().slice(0, 10)} onChange={(event) => void changeDate(event.target.value)} /></label><label>NUEVA HORA<select value={time} onChange={(event) => setTime(event.target.value)}><option value="">Selecciona una hora</option>{times.map((item) => <option value={item} key={item}>{item}</option>)}</select></label><button className="submit-button" disabled={!date || !time || saving} onClick={save}>{saving ? "GUARDANDO…" : "GUARDAR CAMBIOS"}</button></div>{error && <p className="error">{error}</p>}<button className="cancel-appointment" disabled={saving} onClick={cancel}>Cancelar mi cita</button><p className="private-link-note">No compartas este enlace: permite modificar o cancelar tu reserva.</p></section></main>;
}
