"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createSupabaseBrowserClient } from "../../lib/supabase/client";

type Appointment = { id: number; appointmentDate: string; appointmentTime: string; serviceName: string | null; serviceDuration: number | null; priceCents: number | null; customerName: string; customerPhone: string; customerEmail: string };
type Service = { code: string; name: string; durationMinutes: number; priceCents: number };
type Barber = { id: string; name: string; email: string };
type AbsenceReason = "vacation" | "illness" | "personal" | "holiday" | "other";
type DateBlock = { id: number; start_date: string; end_date: string; label: string; reason: AbsenceReason; note: string | null };
type DashboardData = { appointments: Appointment[]; activeTimes: string[]; defaultTimes: string[]; services: Service[]; blocks: DateBlock[] };
type AbsenceDraft = { id?: number; reason: AbsenceReason; startDate: string; endDate: string; indefinite: boolean; note: string };
type AffectedAppointment = { id: number; appointment_date: string; appointment_time: string; customer_name: string; service_name: string | null };

const REASONS: Record<AbsenceReason, string> = { vacation: "Vacaciones", illness: "Enfermedad", personal: "Asunto personal", holiday: "Festivo", other: "Otro" };
function localISO(date = new Date()) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function addDays(value: string, amount: number) { const result = new Date(`${value}T12:00:00`); result.setDate(result.getDate() + amount); return localISO(result); }
function prettyDate(value: string) { return new Intl.DateTimeFormat("es-ES", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date(`${value}T12:00:00`)); }
function emptyAbsence(startDate = localISO()): AbsenceDraft { return { reason: "vacation", startDate, endDate: startDate, indefinite: false, note: "" }; }

export default function BarberDashboard({ barber }: { barber: Barber }) {
  const router = useRouter();
  const [date, setDate] = useState(localISO());
  const [data, setData] = useState<DashboardData>({ appointments: [], activeTimes: [], defaultTimes: [], services: [], blocks: [] });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [customTime, setCustomTime] = useState("");
  const [editing, setEditing] = useState<Appointment | null>(null);
  const [newDate, setNewDate] = useState("");
  const [newTime, setNewTime] = useState("");
  const [absence, setAbsence] = useState<AbsenceDraft | null>(null);
  const [absenceStep, setAbsenceStep] = useState<"form" | "confirm">("form");
  const [affectedAppointments, setAffectedAppointments] = useState(0);
  const [affectedPreview, setAffectedPreview] = useState<AffectedAppointment[]>([]);
  const [savingAbsence, setSavingAbsence] = useState(false);

  const load = useCallback(async () => {
    try { const response = await fetch(`/api/barber?date=${date}`); const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo cargar la agenda."); }
    finally { setLoading(false); }
  }, [date]);
  useEffect(() => {
    let active = true;
    fetch(`/api/barber?date=${date}`).then(async (response) => {
      const body = await response.json(); if (!response.ok) throw new Error(body.error); if (active) setData(body);
    }).catch((caught) => { if (active) setError(caught instanceof Error ? caught.message : "No se pudo cargar la agenda."); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [date]);

  const occupied = useMemo(() => new Set(data.appointments.map((item) => item.appointmentTime)), [data.appointments]);
  async function mutate(body: Record<string, unknown>) { setError(""); const response = await fetch("/api/barber", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) { setError(result.error); return null; } await load(); return result; }
  async function cancel(appointment: Appointment) { if (window.confirm(`¿Cancelar la cita de ${appointment.customerName} a las ${appointment.appointmentTime}?`)) await mutate({ action: "cancel", id: appointment.id }); }
  function openEdit(appointment: Appointment) { setEditing(appointment); setNewDate(appointment.appointmentDate); setNewTime(appointment.appointmentTime); }
  async function saveEdit() { if (!editing || !newDate || !newTime) return; if (await mutate({ action: "reschedule", id: editing.id, date: newDate, time: newTime })) setEditing(null); }
  async function toggle(time: string) { if (occupied.has(time) && data.activeTimes.includes(time)) { setError("No puedes quitar una hora que ya tiene una cita reservada."); return; } await mutate({ action: "availability", date, time, enabled: !data.activeTimes.includes(time) }); }
  async function addTime() { if (!customTime) return; if (await mutate({ action: "availability", date, time: customTime, enabled: true })) setCustomTime(""); }
  async function updateService(service: Service) { const priceInput = document.getElementById(`price-${service.code}`) as HTMLInputElement | null; const durationInput = document.getElementById(`duration-${service.code}`) as HTMLInputElement | null; const price = Number(priceInput?.value.replace(",", ".")); const duration = Number(durationInput?.value); if (!Number.isFinite(price) || price < 0) { setError("Introduce un precio válido."); return; } if (!Number.isInteger(duration) || duration < 5) { setError("Introduce una duración válida de al menos 5 minutos."); return; } await mutate({ action: "service_update", code: service.code, priceCents: Math.round(price * 100), durationMinutes: duration }); }
  function openAbsence(startDate = date, endDate = startDate, reason: AbsenceReason = "vacation") { setAbsence({ ...emptyAbsence(startDate), endDate, reason }); setAbsenceStep("form"); setAffectedAppointments(0); setAffectedPreview([]); }
  function editAbsence(block: DateBlock) { setAbsence({ id: block.id, reason: block.reason ?? "other", startDate: block.start_date, endDate: block.end_date === "9999-12-31" ? block.start_date : block.end_date, indefinite: block.end_date === "9999-12-31", note: block.note ?? "" }); setAbsenceStep("form"); }
  async function reviewAbsence() { if (!absence) return; if (!absence.startDate || (!absence.indefinite && !absence.endDate) || (!absence.indefinite && absence.endDate < absence.startDate)) { setError("Revisa las fechas de la ausencia."); return; } setSavingAbsence(true); const result = await mutate({ action: "absence_preview", startDate: absence.startDate, endDate: absence.indefinite ? "9999-12-31" : absence.endDate }); setSavingAbsence(false); if (result) { setAffectedAppointments(result.affectedAppointments ?? 0); setAffectedPreview(result.affectedPreview ?? []); setAbsenceStep("confirm"); } }
  async function saveAbsence() { if (!absence) return; setSavingAbsence(true); const result = await mutate({ action: "save_absence", id: absence.id, startDate: absence.startDate, endDate: absence.indefinite ? "9999-12-31" : absence.endDate, reason: absence.reason, note: absence.note, label: REASONS[absence.reason] }); setSavingAbsence(false); if (result) setAbsence(null); }
  async function removeAbsence(block: DateBlock) { if (window.confirm(`¿Volver a aceptar reservas durante «${REASONS[block.reason] ?? block.label}»?`)) await mutate({ action: "unblock_range", id: block.id }); }
  async function signOut() { await createSupabaseBrowserClient().auth.signOut(); router.refresh(); }

  return <main className="dashboard-page">
    <aside className="dashboard-side">
      <div className="dashboard-brand"><div className="andalusian-star"><i /><i /></div><div><b>GLORIA BENDITA</b><span>Zona de peluqueros</span></div></div>
      <nav><button className="active">Agenda</button><button onClick={() => document.getElementById("ausencias")?.scrollIntoView({ behavior: "smooth" })}>Ausencias</button><button onClick={() => document.getElementById("servicios")?.scrollIntoView({ behavior: "smooth" })}>Servicios y precios</button><button onClick={() => document.getElementById("horarios")?.scrollIntoView({ behavior: "smooth" })}>Disponibilidad</button></nav>
      <div className="barber-session"><span>{barber.name.split(" ").map((part) => part[0]).join("")}</span><div><b>{barber.name}</b><small>{barber.email}</small></div></div><button className="sign-out" onClick={signOut}>Cerrar sesión</button>
    </aside>
    <section className="dashboard-content">
      <header className="dashboard-header"><div><p>MI AGENDA</p><h1>Buenos días, {barber.name.split(" ")[0]}</h1></div><label>FECHA<input type="date" value={date} onChange={(event) => { setLoading(true); setError(""); setDate(event.target.value); }} /></label></header>
      <div className="day-title"><div><span>{new Date(`${date}T12:00:00`).getDate()}</span><div><b>{prettyDate(date)}</b><small>{data.appointments.length} {data.appointments.length === 1 ? "cita" : "citas"} reservadas</small></div></div><div className="day-actions"><button onClick={() => setDate(localISO())}>Hoy</button><button className="close-day" onClick={() => openAbsence(date, date, "illness")}>Cerrar este día</button></div></div>
      {error && <p className="dashboard-error" role="alert">{error}</p>}
      <section className="appointments-panel"><h2>Citas del día</h2>{loading ? <p className="empty-state">Cargando agenda…</p> : data.appointments.length === 0 ? <p className="empty-state">No tienes citas para este día.</p> : <div className="appointment-list">{data.appointments.map((appointment) => <article className="appointment-card" key={appointment.id}><time>{appointment.appointmentTime}</time><div className="appointment-person"><b>{appointment.customerName}</b><strong>{appointment.serviceName ?? "Servicio no indicado"} · {appointment.serviceDuration ?? 30} min · {((appointment.priceCents ?? 0) / 100).toFixed(2).replace(".00", "").replace(".", ",")} €</strong><span>{appointment.customerPhone} · {appointment.customerEmail}</span></div><div className="appointment-actions"><a href={`tel:${appointment.customerPhone}`}>Llamar</a><button onClick={() => openEdit(appointment)}>Cambiar</button><button className="danger" onClick={() => cancel(appointment)}>Cancelar</button></div></article>)}</div>}</section>
      <section className="closures-panel" id="ausencias"><div className="panel-heading"><div><p>AUSENCIAS Y CIERRES</p><h2>Gestiona los días que no trabajas</h2><span>Vacaciones, enfermedad, festivos o cualquier periodo en el que no quieras recibir reservas.</span></div><button className="primary-panel-action" onClick={() => openAbsence()}>+ Añadir ausencia</button></div><div className="quick-closures"><button onClick={() => openAbsence(localISO(), localISO(), "illness")}><b>Cerrar hoy</b><span>Para una baja o imprevisto</span></button><button onClick={() => { const tomorrow = addDays(localISO(), 1); openAbsence(tomorrow, tomorrow, "personal"); }}><b>Cerrar mañana</b><span>Un solo día</span></button><button onClick={() => openAbsence(localISO(), addDays(localISO(), 6), "vacation")}><b>Próximos 7 días</b><span>Rango rápido</span></button></div>{data.blocks.length === 0 ? <p className="empty-absence">No tienes ausencias próximas programadas.</p> : <div className="closure-list"><h3>Próximas ausencias</h3>{data.blocks.map((block) => <article key={block.id}><span className={`absence-icon ${block.reason}`}>{block.reason === "vacation" ? "☀" : block.reason === "illness" ? "+" : block.reason === "holiday" ? "★" : "•"}</span><div><b>{REASONS[block.reason] ?? block.label}</b><span>{block.end_date === "9999-12-31" ? `Desde ${prettyDate(block.start_date)} · Sin fecha de regreso` : block.start_date === block.end_date ? prettyDate(block.start_date) : `${prettyDate(block.start_date)} — ${prettyDate(block.end_date)}`}</span>{block.note && <small>{block.note}</small>}</div><div className="absence-actions"><button onClick={() => editAbsence(block)}>Editar</button><button className="danger" onClick={() => removeAbsence(block)}>Finalizar / eliminar</button></div></article>)}</div>}</section>
      <section className="services-panel" id="servicios"><div className="panel-heading"><div><p>SERVICIOS</p><h2>Precio y duración de {barber.name}</h2><span>Los cambios solo afectan a las nuevas reservas.</span></div></div><div className="price-grid">{data.services.map((service) => <article key={service.code}><div><b>{service.name}</b><small>Configura cuánto cuesta y cuánto tiempo ocupa.</small></div><label>PRECIO<div><input type="number" min="0" step="0.50" defaultValue={(service.priceCents / 100).toFixed(2)} id={`price-${service.code}`} /><span>€</span></div></label><label>DURACIÓN<div><input type="number" min="5" max="480" step="5" defaultValue={service.durationMinutes} id={`duration-${service.code}`} /><span>min</span></div></label><button onClick={() => void updateService(service)}>Guardar cambios</button></article>)}</div></section>
      <section className="availability-panel" id="horarios"><div className="panel-heading"><div><p>DISPONIBILIDAD POR HORAS</p><h2>Ajustes del {prettyDate(date)}</h2><span>Para cambios puntuales de horas. Usa Ausencias si no trabajarás durante el día completo.</span></div><div className="add-time"><input aria-label="Nueva hora" type="time" value={customTime} onChange={(event) => setCustomTime(event.target.value)} /><button onClick={addTime}>Añadir hora</button></div></div><div className="availability-grid">{[...new Set([...data.defaultTimes, ...data.activeTimes])].sort().map((time) => { const enabled = data.activeTimes.includes(time); return <button key={time} className={enabled ? "enabled" : "disabled"} onClick={() => toggle(time)}><b>{time}</b><span>{occupied.has(time) ? "Reservada" : enabled ? "Disponible" : "No disponible"}</span><i>{enabled ? "✓" : "+"}</i></button>; })}</div></section>
    </section>
    {editing && <div className="modal-backdrop" role="presentation"><div className="edit-modal" role="dialog" aria-modal="true" aria-labelledby="edit-title"><button className="modal-close" onClick={() => setEditing(null)}>×</button><p>CAMBIAR CITA</p><h2 id="edit-title">{editing.customerName}</h2><label>NUEVA FECHA<input type="date" value={newDate} onChange={(event) => setNewDate(event.target.value)} /></label><label>NUEVA HORA<input type="time" value={newTime} onChange={(event) => setNewTime(event.target.value)} /></label><button className="save-change" onClick={saveEdit}>Guardar cambios</button></div></div>}
    {absence && <div className="modal-backdrop" role="presentation"><div className="absence-modal" role="dialog" aria-modal="true" aria-labelledby="absence-title"><button className="modal-close" onClick={() => setAbsence(null)}>×</button><p>AUSENCIAS</p><h2 id="absence-title">{absence.id ? "Editar ausencia" : "Añadir ausencia"}</h2>{absenceStep === "form" ? <><label>MOTIVO<select value={absence.reason} onChange={(event) => setAbsence({ ...absence, reason: event.target.value as AbsenceReason })}>{Object.entries(REASONS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="absence-date-row"><label>DESDE<input type="date" value={absence.startDate} onChange={(event) => setAbsence({ ...absence, startDate: event.target.value, endDate: absence.endDate < event.target.value ? event.target.value : absence.endDate })} /></label><label>HASTA<input type="date" value={absence.endDate} disabled={absence.indefinite} min={absence.startDate} onChange={(event) => setAbsence({ ...absence, endDate: event.target.value })} /></label></div><label className="indefinite-check"><input type="checkbox" checked={absence.indefinite} onChange={(event) => setAbsence({ ...absence, indefinite: event.target.checked })} /> Todavía no sé cuándo volveré</label><label>NOTA OPCIONAL<textarea maxLength={300} value={absence.note} onChange={(event) => setAbsence({ ...absence, note: event.target.value })} placeholder="Ej. Vacaciones de verano" /></label><button className="save-change" onClick={reviewAbsence} disabled={savingAbsence}>{savingAbsence ? "REVISANDO…" : "REVISAR AUSENCIA"}</button></> : <div className="absence-confirm"><span className="confirm-icon">!</span><h3>{affectedAppointments === 0 ? "No hay citas afectadas" : `${affectedAppointments} ${affectedAppointments === 1 ? "cita afectada" : "citas afectadas"}`}</h3><p>La ausencia impedirá nuevas reservas durante este periodo. Las citas que ya existen se mantendrán activas y podrás gestionarlas desde la agenda.</p>{affectedPreview.length > 0 && <div className="affected-list">{affectedPreview.map((item) => <article key={item.id}><b>{prettyDate(item.appointment_date)} · {item.appointment_time.slice(0, 5)}</b><span>{item.customer_name} · {item.service_name ?? "Servicio"}</span></article>)}{affectedAppointments > affectedPreview.length && <small>Y {affectedAppointments - affectedPreview.length} citas más…</small>}</div>}<div className="confirm-actions"><button onClick={() => setAbsenceStep("form")}>Volver</button><button className="confirm-absence" onClick={saveAbsence} disabled={savingAbsence}>{savingAbsence ? "GUARDANDO…" : "CONFIRMAR AUSENCIA"}</button></div></div>}</div></div>}
  </main>;
}
