import { BARBERS, DEFAULT_TIMES } from "../../../../lib/barbers";
import { hashManagementToken } from "../../../../lib/management";
import { intervalsOverlap, timeToMinutes } from "../../../../lib/services";
import { createSupabaseAdminClient } from "../../../../lib/supabase/admin";
const datePattern = /^\d{4}-\d{2}-\d{2}$/; const timePattern = /^([01]\d|2[0-3]):[0-5]\d$/; const shortTime = (value: string) => value.slice(0, 5);
function mapAppointment(row: Record<string, unknown>) { return { id: row.id, barber: row.barber_id, appointmentDate: row.appointment_date, appointmentTime: shortTime(String(row.appointment_time)), serviceCode: row.service_code, serviceName: row.service_name, serviceDuration: row.service_duration, priceCents: row.price_cents, customerName: row.customer_name, customerPhone: row.customer_phone, customerEmail: row.customer_email, status: row.status }; }
async function findAppointment(token: string) { const hash = await hashManagementToken(token); const { data } = await createSupabaseAdminClient().from("reservations").select("*").eq("management_token_hash", hash).maybeSingle(); return data ? mapAppointment(data) : null; }
async function timesFor(barber: string, date: string, currentId: number, duration: number) { const db = createSupabaseAdminClient(); const [overrides, booked] = await Promise.all([db.from("availability_overrides").select("appointment_time, enabled").eq("barber_id", barber).eq("appointment_date", date), db.from("reservations").select("appointment_time, service_duration").eq("barber_id", barber).eq("appointment_date", date).eq("status", "confirmed").neq("id", currentId)]); const active = new Set(DEFAULT_TIMES); for (const row of overrides.data ?? []) { const time = shortTime(row.appointment_time); if (row.enabled) active.add(time); else active.delete(time); } return [...active].filter((candidate) => !(booked.data ?? []).some((row) => intervalsOverlap(timeToMinutes(candidate), duration, timeToMinutes(shortTime(row.appointment_time)), row.service_duration ?? 30))).sort(); }
export async function GET(request: Request, context: { params: Promise<{ token: string }> }) { const { token } = await context.params; const appointment = await findAppointment(token); if (!appointment) return Response.json({ error: "La cita no existe o el enlace ya no es válido." }, { status: 404 }); const requestedDate = new URL(request.url).searchParams.get("date") || String(appointment.appointmentDate); if (!datePattern.test(requestedDate)) return Response.json({ error: "Fecha incorrecta" }, { status: 400 }); const barber = BARBERS[appointment.barber as keyof typeof BARBERS]; return Response.json({ appointment: { ...appointment, barberName: barber?.name ?? "Peluquero" }, availableTimes: await timesFor(String(appointment.barber), requestedDate, Number(appointment.id), Number(appointment.serviceDuration ?? 30)) }); }
export async function PATCH(request: Request, context: { params: Promise<{ token: string }> }) { const { token } = await context.params; const appointment = await findAppointment(token); if (!appointment) return Response.json({ error: "La cita no existe o el enlace ya no es válido." }, { status: 404 }); const body = await request.json() as Record<string, unknown>; const action = String(body.action ?? ""); const db = createSupabaseAdminClient(); if (action === "cancel") { await db.from("reservations").update({ status: "cancelled" }).eq("id", appointment.id); return Response.json({ ok: true, cancelled: true }); } if (action === "reschedule") { const date = String(body.date ?? ""), time = String(body.time ?? ""); if (!datePattern.test(date) || !timePattern.test(time)) return Response.json({ error: "Selecciona una fecha y una hora válidas." }, { status: 400 }); const times = await timesFor(String(appointment.barber), date, Number(appointment.id), Number(appointment.serviceDuration ?? 30)); if (!times.includes(time)) return Response.json({ error: "Esa hora ya no está disponible." }, { status: 409 }); const { error } = await db.from("reservations").update({ appointment_date: date, appointment_time: time }).eq("id", appointment.id); if (error) return Response.json({ error: "Esa hora acaba de ser reservada." }, { status: 409 }); return Response.json({ ok: true }); } return Response.json({ error: "Acción incorrecta" }, { status: 400 }); }
