create extension if not exists pgcrypto;

create table public.barbers (
  id text primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table public.barber_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  barber_id text not null references public.barbers(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.barber_services (
  id bigint generated by default as identity primary key,
  barber_id text not null references public.barbers(id) on delete cascade,
  code text not null,
  name text not null,
  duration_minutes integer not null check (duration_minutes > 0),
  price_cents integer not null check (price_cents >= 0),
  enabled boolean not null default true,
  unique (barber_id, code)
);

create table public.availability_overrides (
  id bigint generated by default as identity primary key,
  barber_id text not null references public.barbers(id) on delete cascade,
  appointment_date date not null,
  appointment_time time not null,
  enabled boolean not null,
  created_at timestamptz not null default now(),
  unique (barber_id, appointment_date, appointment_time)
);

create table public.reservations (
  id bigint generated by default as identity primary key,
  barber_id text not null references public.barbers(id) on delete restrict,
  appointment_date date not null,
  appointment_time time not null,
  service_code text,
  service_name text,
  service_duration integer,
  price_cents integer,
  customer_name text not null,
  customer_phone text not null,
  customer_email text not null,
  management_token_hash text unique,
  status text not null default 'confirmed' check (status in ('confirmed', 'cancelled')),
  created_at timestamptz not null default now(),
  unique (barber_id, appointment_date, appointment_time)
);

create index reservations_barber_date_idx
  on public.reservations (barber_id, appointment_date);

insert into public.barbers (id, name) values
  ('peluquero-1', 'Javi Pérez'),
  ('peluquero-2', 'Iván')
on conflict (id) do update set name = excluded.name;

insert into public.barber_services
  (barber_id, code, name, duration_minutes, price_cents)
values
  ('peluquero-1', 'corte', 'Corte', 45, 1000),
  ('peluquero-1', 'barba', 'Barba', 30, 1000),
  ('peluquero-1', 'corte-barba', 'Corte + barba', 60, 1500),
  ('peluquero-2', 'corte', 'Corte', 45, 1000),
  ('peluquero-2', 'barba', 'Barba', 30, 1000),
  ('peluquero-2', 'corte-barba', 'Corte + barba', 60, 1500)
on conflict (barber_id, code) do nothing;

-- Después de crear cada cuenta en Supabase Auth, vincúlala con su peluquero:
-- insert into public.barber_users (user_id, barber_id)
-- select id, 'peluquero-1' from auth.users where lower(email) = 'correo@ejemplo.com'
-- on conflict (user_id) do update set barber_id = excluded.barber_id;

alter table public.barbers enable row level security;
alter table public.barber_users enable row level security;
alter table public.barber_services enable row level security;
alter table public.availability_overrides enable row level security;
alter table public.reservations enable row level security;

create policy "public can read barbers"
on public.barbers for select
to anon, authenticated
using (true);

create policy "public can read enabled services"
on public.barber_services for select
to anon, authenticated
using (enabled or exists (
  select 1 from public.barber_users bu
  where bu.user_id = auth.uid() and bu.barber_id = barber_services.barber_id
));

create policy "barbers can update own services"
on public.barber_services for update
to authenticated
using (exists (
  select 1 from public.barber_users bu
  where bu.user_id = auth.uid() and bu.barber_id = barber_services.barber_id
))
with check (exists (
  select 1 from public.barber_users bu
  where bu.user_id = auth.uid() and bu.barber_id = barber_services.barber_id
));

create policy "barbers can read own account"
on public.barber_users for select
to authenticated
using (user_id = auth.uid());

create policy "public can read availability"
on public.availability_overrides for select
to anon, authenticated
using (true);

create policy "barbers manage own availability"
on public.availability_overrides for all
to authenticated
using (exists (
  select 1 from public.barber_users bu
  where bu.user_id = auth.uid() and bu.barber_id = availability_overrides.barber_id
))
with check (exists (
  select 1 from public.barber_users bu
  where bu.user_id = auth.uid() and bu.barber_id = availability_overrides.barber_id
));

create policy "barbers read own reservations"
on public.reservations for select
to authenticated
using (exists (
  select 1 from public.barber_users bu
  where bu.user_id = auth.uid() and bu.barber_id = reservations.barber_id
));

create policy "barbers update own reservations"
on public.reservations for update
to authenticated
using (exists (
  select 1 from public.barber_users bu
  where bu.user_id = auth.uid() and bu.barber_id = reservations.barber_id
))
with check (exists (
  select 1 from public.barber_users bu
  where bu.user_id = auth.uid() and bu.barber_id = reservations.barber_id
));
