create table public.availability_blocks (
  id bigint generated by default as identity primary key,
  barber_id text not null references public.barbers(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  label text not null,
  created_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create index availability_blocks_barber_dates_idx
  on public.availability_blocks (barber_id, start_date, end_date);

alter table public.availability_blocks enable row level security;

create policy "public can read date blocks"
on public.availability_blocks for select to anon, authenticated using (true);

create policy "barbers manage own date blocks"
on public.availability_blocks for all to authenticated
using (exists (select 1 from public.barber_users bu where bu.user_id = auth.uid() and bu.barber_id = availability_blocks.barber_id))
with check (exists (select 1 from public.barber_users bu where bu.user_id = auth.uid() and bu.barber_id = availability_blocks.barber_id));
